"""Audit log model for event-driven architecture"""
from sqlmodel import SQLModel, Field, Column
from sqlalchemy.dialects.postgresql import JSONB
from datetime import datetime
from typing import Optional
from uuid import UUID


class AuditLogBase(SQLModel):
    """Base audit log fields"""
    event_id: UUID = Field(unique=True, nullable=False, description="UUID from Kafka event (idempotency key)")
    timestamp: datetime = Field(nullable=False, description="Original event timestamp from Kafka")
    user_id: int = Field(foreign_key="users.id", nullable=False, description="User who performed operation")
    task_id: Optional[int] = Field(default=None, foreign_key="tasks.id", description="Task affected (NULL for non-task events)")
    operation_type: str = Field(
        max_length=50,
        nullable=False,
        description="Event type: task.created, task.updated, task.deleted, task.completed"
    )
    event_payload: dict = Field(
        sa_column=Column(JSONB, nullable=False),
        description="Full event JSON for forensic analysis"
    )
    system_generated: bool = Field(
        default=False,
        description="TRUE if event was generated by Recurring Task Service"
    )


class AuditLog(AuditLogBase, table=True):
    """Audit log database model"""
    __tablename__ = "audit_logs"

    id: Optional[int] = Field(default=None, primary_key=True)
    created_at: datetime = Field(default_factory=datetime.utcnow, description="Database insertion timestamp")

    class Config:
        arbitrary_types_allowed = True


class AuditLogCreate(AuditLogBase):
    """Schema for creating an audit log entry"""
    pass


class AuditLogRead(AuditLogBase):
    """Schema for reading an audit log entry"""
    id: int
    created_at: datetime


# Type alias for operation types (for validation)
VALID_OPERATION_TYPES = {
    "task.created",
    "task.updated",
    "task.deleted",
    "task.completed"
}


def validate_operation_type(operation_type: str) -> bool:
    """Validate that operation_type is one of the allowed values"""
    return operation_type in VALID_OPERATION_TYPES
