apiVersion: v1
kind: Secret
metadata:
  name: {{ include "audit-service.fullname" . }}
  labels:
    {{- include "audit-service.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_URL: {{ .Values.database.url | b64enc | quote }}
  {{- if .Values.kafka.sasl.enabled }}
  KAFKA_SASL_USERNAME: {{ .Values.kafka.sasl.username | b64enc | quote }}
  KAFKA_SASL_PASSWORD: {{ .Values.kafka.sasl.password | b64enc | quote }}
  {{- end }}
