-- Migration: 004_add_kafka_event_schema
-- Feature: Event-Driven Architecture with Kafka
-- Date: 2026-01-12
-- Purpose: Add audit_logs, notification_subscriptions, and idempotency constraints
-- Risk Level: Low (all new tables/indexes with backward compatibility)
-- Estimated Duration: 5-10 seconds on production
-- Downtime Required: No

BEGIN;

-- ============================================================================
-- 1. CREATE AUDIT_LOGS TABLE
-- ============================================================================
-- Purpose: Store comprehensive audit trail of all task operations from Kafka events
-- Retention: 90 days (manual cleanup via cron job)

CREATE TABLE IF NOT EXISTS audit_logs (
    id SERIAL PRIMARY KEY,
    event_id UUID UNIQUE NOT NULL,              -- Idempotency key from Kafka event
    timestamp TIMESTAMPTZ NOT NULL,             -- Original event timestamp (not insertion time)
    user_id VARCHAR(255) NOT NULL,              -- User who performed the operation
    task_id INTEGER,                            -- Task affected (NULL for non-task events)
    operation_type VARCHAR(50) NOT NULL,        -- Event type (task.created, task.updated, etc.)
    event_payload JSONB NOT NULL,               -- Full event JSON for forensic analysis
    system_generated BOOLEAN DEFAULT FALSE,     -- TRUE if auto-generated by Recurring Task Service
    created_at TIMESTAMPTZ DEFAULT NOW(),       -- Database insertion timestamp

    -- Foreign key constraints
    CONSTRAINT fk_audit_logs_user_id
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_audit_logs_task_id
        FOREIGN KEY (task_id)
        REFERENCES tasks(id)
        ON DELETE SET NULL,                     -- Keep audit log even if task deleted

    -- Validation constraints
    CONSTRAINT chk_audit_logs_operation_type
        CHECK (operation_type IN ('task.created', 'task.updated', 'task.deleted', 'task.completed')),

    CONSTRAINT chk_audit_logs_timestamp
        CHECK (timestamp <= NOW() + INTERVAL '1 hour')  -- Prevent far-future timestamps
);

-- Add comment for documentation
COMMENT ON TABLE audit_logs IS 'Audit trail of all task operations consumed from Kafka task-events topic';
COMMENT ON COLUMN audit_logs.event_id IS 'UUID from Kafka event (enforces idempotency via UNIQUE constraint)';
COMMENT ON COLUMN audit_logs.timestamp IS 'Original event timestamp from Kafka message';
COMMENT ON COLUMN audit_logs.system_generated IS 'TRUE if event was generated by Recurring Task Service';

-- ============================================================================
-- 2. CREATE INDEXES ON AUDIT_LOGS
-- ============================================================================
-- Purpose: Optimize queries for audit log retrieval and analysis

-- Partial index: Only index rows with non-NULL task_id (saves space)
CREATE INDEX idx_audit_logs_task_id
    ON audit_logs(task_id)
    WHERE task_id IS NOT NULL;

-- Index for querying by user
CREATE INDEX idx_audit_logs_user_id
    ON audit_logs(user_id);

-- Index for querying by timestamp (DESC for recent-first sorting)
CREATE INDEX idx_audit_logs_timestamp
    ON audit_logs(timestamp DESC);

-- Index for filtering by operation type
CREATE INDEX idx_audit_logs_operation_type
    ON audit_logs(operation_type);

-- Optional: GIN index for full-text search on event payload (uncomment if needed)
-- CREATE INDEX idx_audit_logs_payload_gin
--     ON audit_logs USING gin(event_payload);

-- ============================================================================
-- 3. ADD IDEMPOTENCY CONSTRAINT TO TASKS TABLE
-- ============================================================================
-- Purpose: Prevent duplicate recurring instances from being created
-- Strategy: Unique constraint on (parent_task_id, due_date) for recurring instances

CREATE UNIQUE INDEX IF NOT EXISTS idx_recurring_instance_dedup
    ON tasks(parent_task_id, due_date)
    WHERE parent_task_id IS NOT NULL;

COMMENT ON INDEX idx_recurring_instance_dedup IS 'Prevents duplicate recurring task instances for same parent and due_date';

-- ============================================================================
-- 4. CREATE NOTIFICATION_SUBSCRIPTIONS TABLE
-- ============================================================================
-- Purpose: Store Web Push notification subscriptions for browser notifications
-- Alternative: Can store in frontend localStorage if simpler for MVP

CREATE TABLE IF NOT EXISTS notification_subscriptions (
    id SERIAL PRIMARY KEY,
    user_id VARCHAR(255) NOT NULL,              -- User who granted notification permission
    endpoint TEXT NOT NULL,                     -- Push service endpoint (e.g., FCM URL)
    p256dh TEXT NOT NULL,                       -- Client public key for message encryption
    auth TEXT NOT NULL,                         -- Authentication secret for encryption
    created_at TIMESTAMPTZ DEFAULT NOW(),       -- Subscription creation timestamp
    updated_at TIMESTAMPTZ DEFAULT NOW(),       -- Last subscription update

    -- Foreign key constraint
    CONSTRAINT fk_notification_subs_user_id
        FOREIGN KEY (user_id)
        REFERENCES users(id)
        ON DELETE CASCADE,

    -- Prevent duplicate subscriptions for same user+endpoint
    CONSTRAINT uk_notification_subs_user_endpoint
        UNIQUE(user_id, endpoint)
);

-- Add comment for documentation
COMMENT ON TABLE notification_subscriptions IS 'Web Push notification subscriptions for browser notifications';
COMMENT ON COLUMN notification_subscriptions.endpoint IS 'Push service URL (unique per browser/device)';
COMMENT ON COLUMN notification_subscriptions.p256dh IS 'Public key for encrypting push messages (VAPID)';
COMMENT ON COLUMN notification_subscriptions.auth IS 'Authentication secret for message verification';

-- ============================================================================
-- 5. CREATE INDEX ON NOTIFICATION_SUBSCRIPTIONS
-- ============================================================================
-- Purpose: Fast lookup of subscriptions by user

CREATE INDEX idx_notification_subs_user_id
    ON notification_subscriptions(user_id);

-- ============================================================================
-- VERIFICATION QUERIES
-- ============================================================================
-- Run these queries after migration to verify success

-- Verify audit_logs table exists with correct columns
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'audit_logs'
    ) THEN
        RAISE EXCEPTION 'audit_logs table was not created';
    END IF;
END $$;

-- Verify notification_subscriptions table exists
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'notification_subscriptions'
    ) THEN
        RAISE EXCEPTION 'notification_subscriptions table was not created';
    END IF;
END $$;

-- Verify idempotency index exists on tasks
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_indexes
        WHERE indexname = 'idx_recurring_instance_dedup'
    ) THEN
        RAISE EXCEPTION 'idx_recurring_instance_dedup index was not created';
    END IF;
END $$;

COMMIT;

-- ============================================================================
-- POST-MIGRATION VALIDATION
-- ============================================================================
-- Run these queries manually after migration to verify success:

/*
-- 1. Verify audit_logs table structure
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'audit_logs'
ORDER BY ordinal_position;

-- 2. Verify audit_logs indexes
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'audit_logs';

-- 3. Verify idempotency constraint on tasks
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'tasks' AND indexname = 'idx_recurring_instance_dedup';

-- 4. Verify notification_subscriptions table structure
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_name = 'notification_subscriptions'
ORDER BY ordinal_position;

-- 5. Verify notification_subscriptions indexes
SELECT indexname, indexdef
FROM pg_indexes
WHERE tablename = 'notification_subscriptions';

-- 6. Test audit_logs insert (should succeed)
INSERT INTO audit_logs (
    event_id, timestamp, user_id, task_id, operation_type, event_payload, system_generated
) VALUES (
    gen_random_uuid(),
    NOW(),
    1,
    1,
    'task.created',
    '{"test": "data"}'::jsonb,
    false
);

-- 7. Test duplicate event_id (should fail with unique constraint violation)
-- INSERT INTO audit_logs (event_id, timestamp, user_id, operation_type, event_payload)
-- VALUES ('550e8400-e29b-41d4-a716-446655440000', NOW(), 1, 'task.created', '{}'::jsonb);
-- Expected: ERROR: duplicate key value violates unique constraint "audit_logs_event_id_key"

-- 8. Verify constraint on operation_type (should fail)
-- INSERT INTO audit_logs (event_id, timestamp, user_id, operation_type, event_payload)
-- VALUES (gen_random_uuid(), NOW(), 1, 'invalid.type', '{}'::jsonb);
-- Expected: ERROR: new row violates check constraint "chk_audit_logs_operation_type"
*/
