"""Dockerfile generator for docker-ai.

Main component that generates optimized Dockerfiles from specifications.
"""

from typing import Dict, Any, List
from pathlib import Path
import sys

sys.path.insert(0, str(Path(__file__).parent.parent))

from base_image import BaseImageSelector
from multistage import MultiStageBuilder
from security import SecurityHardener
from optimizer import LayerOptimizer
import logging

logger = logging.getLogger(__name__)


class DockerfileGenerator:
    """Generates optimized Dockerfiles."""

    def __init__(
        self,
        config: Any,
        multistage: bool = True,
        security: bool = True,
        optimize: bool = True
    ):
        """Initialize Dockerfile generator.

        Args:
            config: Configuration object
            multistage: Use multi-stage builds
            security: Apply security hardening
            optimize: Optimize layer caching
        """
        self.config = config
        self.use_multistage = multistage
        self.use_security = security
        self.use_optimize = optimize

        self.base_selector = BaseImageSelector(config)
        self.multistage_builder = MultiStageBuilder(config)
        self.security_hardener = SecurityHardener(config) if security else None
        self.optimizer = LayerOptimizer(config) if optimize else None

    def generate_from_spec(self, spec: Dict[str, Any]) -> str:
        """Generate Dockerfile from specification.

        Args:
            spec: Specification dict from NL processor

        Returns:
            Dockerfile content as string
        """
        language = spec.get('language', 'python')
        framework = spec.get('framework')
        services = spec.get('services', [])
        ports = spec.get('ports', [8000])

        # Select base images
        base_images = self.base_selector.select(
            language=language,
            framework=framework,
            optimize_size=self.use_optimize
        )

        # Generate Dockerfile
        if self.use_multistage and self.multistage_builder.should_use_multistage(language):
            dockerfile = self._generate_multistage(
                language, framework, base_images, ports, services
            )
        else:
            dockerfile = self._generate_simple(
                language, framework, base_images, ports, services
            )

        return dockerfile

    def generate_from_analysis(self, analysis: Dict[str, Any], project_path: Path) -> str:
        """Generate Dockerfile from code analysis.

        Args:
            analysis: Analysis result from CodeAnalyzer
            project_path: Path to project

        Returns:
            Dockerfile content
        """
        language = analysis.get('language', 'python')
        framework = analysis.get('framework')
        dependencies = analysis.get('dependencies', [])
        entry_point = analysis.get('entry_point', 'main')
        ports = analysis.get('ports', [8000])

        # Select base images
        base_images = self.base_selector.select(language, framework)

        # Generate
        if self.use_multistage:
            dockerfile = self._generate_multistage(
                language, framework, base_images, ports, [], dependencies, entry_point
            )
        else:
            dockerfile = self._generate_simple(
                language, framework, base_images, ports, [], dependencies, entry_point
            )

        return dockerfile

    def _generate_simple(
        self,
        language: str,
        framework: str,
        base_images: Dict[str, str],
        ports: List[int],
        services: List[str] = None,
        dependencies: List[str] = None,
        entry_point: str = None
    ) -> str:
        """Generate simple single-stage Dockerfile."""
        lines = []

        # Header comment
        lines.append(f"# Dockerfile for {language}" + (f" {framework}" if framework else ""))
        lines.append(f"# Generated by docker-ai")
        lines.append("")

        # Base image
        lines.append(f"FROM {base_images['runtime']}")
        lines.append("")

        # Working directory
        lines.append("WORKDIR /app")
        lines.append("")

        # Install system dependencies if needed
        if language == 'python':
            packages = self.base_selector.get_recommended_packages(language, framework)
            if packages:
                if 'alpine' in base_images['runtime']:
                    lines.append(f"RUN apk add --no-cache {' '.join(packages)}")
                else:
                    lines.append(f"RUN apt-get update && apt-get install -y {' '.join(packages)} && rm -rf /var/lib/apt/lists/*")
                lines.append("")

        # Copy dependency files
        if language == 'python':
            lines.append("COPY requirements.txt .")
            lines.append("RUN pip install --no-cache-dir -r requirements.txt")
        elif language in ['javascript', 'typescript']:
            lines.append("COPY package*.json ./")
            lines.append("RUN npm ci --only=production")
        elif language == 'go':
            lines.append("COPY go.mod go.sum ./")
            lines.append("RUN go mod download")
        elif language == 'ruby':
            lines.append("COPY Gemfile Gemfile.lock ./")
            lines.append("RUN bundle install")

        lines.append("")

        # Copy application code
        lines.append("COPY . .")
        lines.append("")

        # Security: Create non-root user
        if self.use_security:
            lines.append("# Create non-root user")
            lines.append("RUN addgroup -S appgroup && adduser -S appuser -G appgroup")
            lines.append("RUN chown -R appuser:appgroup /app")
            lines.append("USER appuser")
            lines.append("")

        # Expose ports
        for port in ports:
            lines.append(f"EXPOSE {port}")
        lines.append("")

        # Health check (optional)
        if framework in ['flask', 'fastapi', 'express']:
            lines.append(f"HEALTHCHECK --interval=30s --timeout=3s --retries=3 \\")
            lines.append(f"  CMD wget --quiet --tries=1 --spider http://localhost:{ports[0]}/health || exit 1")
            lines.append("")

        # CMD
        cmd = self._get_cmd(language, framework, entry_point)
        lines.append(f'CMD {cmd}')

        return '\n'.join(lines)

    def _generate_multistage(
        self,
        language: str,
        framework: str,
        base_images: Dict[str, str],
        ports: List[int],
        services: List[str] = None,
        dependencies: List[str] = None,
        entry_point: str = None
    ) -> str:
        """Generate multi-stage Dockerfile."""
        lines = []

        # Header
        lines.append(f"# Multi-stage Dockerfile for {language}" + (f" {framework}" if framework else ""))
        lines.append(f"# Generated by docker-ai")
        lines.append("")

        # Get stages
        stages = self.multistage_builder.create_stages(language, base_images, dependencies)

        if language in ['go', 'rust']:
            # Compiled language stages
            for i, stage in enumerate(stages):
                if i > 0:
                    lines.append("")

                # Stage header
                if stage['name'] == 'builder':
                    lines.append(f"FROM {stage['base']} AS builder")
                else:
                    lines.append(f"FROM {stage['base']}")

                lines.append("")

                # Stage steps
                for step in stage['steps']:
                    lines.append(step)

        elif language in ['javascript', 'typescript']:
            # Node.js multi-stage
            lines.append(f"# Dependencies stage")
            lines.append(f"FROM {base_images['build']} AS dependencies")
            lines.append("WORKDIR /app")
            lines.append("COPY package*.json ./")
            lines.append("RUN npm ci --only=production")
            lines.append("")

            lines.append(f"# Runtime stage")
            lines.append(f"FROM {base_images['runtime']}")
            lines.append("WORKDIR /app")
            lines.append("COPY --from=dependencies /app/node_modules ./node_modules")
            lines.append("COPY . .")

        elif language == 'python':
            # Python can use single stage with optimizations
            return self._generate_simple(
                language, framework, base_images, ports, services, dependencies, entry_point
            )

        # Security and final steps for runtime stage
        if self.use_security:
            lines.append("")
            lines.append("# Security: Create non-root user")
            if 'alpine' in base_images['runtime']:
                lines.append("RUN addgroup -S appgroup && adduser -S appuser -G appgroup")
            else:
                lines.append("RUN groupadd -r appgroup && useradd -r -g appgroup appuser")
            lines.append("RUN chown -R appuser:appgroup /app")
            lines.append("USER appuser")

        # Expose ports
        lines.append("")
        for port in ports:
            lines.append(f"EXPOSE {port}")

        # CMD
        lines.append("")
        cmd = self._get_cmd(language, framework, entry_point)
        lines.append(f'CMD {cmd}')

        return '\n'.join(lines)

    def _get_cmd(self, language: str, framework: str = None, entry_point: str = None) -> str:
        """Get CMD instruction for language/framework."""
        if language == 'python':
            if framework == 'flask':
                ep = entry_point or 'app.py'
                return f'["python", "{ep}"]'
            elif framework == 'django':
                return '["python", "manage.py", "runserver", "0.0.0.0:8000"]'
            elif framework == 'fastapi':
                ep = entry_point or 'main.py'
                ep_module = ep.replace('.py', '')
                return f'["uvicorn", "{ep_module}:app", "--host", "0.0.0.0", "--port", "8000"]'
            else:
                return f'["python", "{entry_point or "main.py"}"]'

        elif language in ['javascript', 'typescript']:
            if framework == 'next':
                return '["npm", "start"]'
            elif framework == 'nest':
                return '["node", "dist/main"]'
            else:
                return f'["node", "{entry_point or "index.js"}"]'

        elif language == 'go':
            return '["./app"]'

        elif language == 'rust':
            return '["./app"]'

        else:
            return '["./app"]'
