#!/usr/bin/env python3
"""
Load Test Script for Kafka Event Architecture
Tests 10,000 events/minute throughput across all services

Usage:
    python load_test.py --events 10000 --duration 60
    python load_test.py --rps 100 --duration 300
"""
import argparse
import asyncio
import json
import time
import uuid
from datetime import datetime, timedelta
from typing import List, Dict
import aiohttp
from kafka import KafkaProducer


class LoadTester:
    """Load testing tool for event-driven architecture"""

    def __init__(
        self,
        api_url: str = "http://localhost:8000",
        kafka_bootstrap: str = "localhost:19092",
        user_id: str = "load-test-user"
    ):
        self.api_url = api_url
        self.kafka_bootstrap = kafka_bootstrap
        self.user_id = user_id

        # Metrics
        self.total_requests = 0
        self.successful_requests = 0
        self.failed_requests = 0
        self.total_latency = 0.0
        self.start_time = None
        self.end_time = None

        # Kafka producer
        self.producer = None

    def connect_kafka(self):
        """Connect to Kafka"""
        self.producer = KafkaProducer(
            bootstrap_servers=self.kafka_bootstrap,
            value_serializer=lambda v: json.dumps(v).encode('utf-8')
        )
        print(f"Connected to Kafka: {self.kafka_bootstrap}")

    def close_kafka(self):
        """Close Kafka connection"""
        if self.producer:
            self.producer.close()
            print("Kafka connection closed")

    async def create_task(self, session: aiohttp.ClientSession, task_num: int) -> Dict:
        """Create a task via REST API"""
        task_data = {
            "title": f"Load test task {task_num}",
            "description": f"Generated by load test at {datetime.utcnow().isoformat()}",
            "user_id": self.user_id,
            "recurring_pattern": "daily" if task_num % 3 == 0 else "none",
            "recurring_interval": 1,
            "due_date": (datetime.utcnow() + timedelta(days=1)).isoformat(),
            "priority": ["low", "medium", "high"][task_num % 3],
            "tags": ["load-test", f"batch-{task_num // 100}"]
        }

        start = time.time()

        try:
            async with session.post(
                f"{self.api_url}/api/{self.user_id}/tasks",
                json=task_data
            ) as response:
                latency = time.time() - start

                self.total_requests += 1
                self.total_latency += latency

                if response.status == 201:
                    self.successful_requests += 1
                    task = await response.json()
                    return {
                        "success": True,
                        "task_id": task["id"],
                        "latency": latency
                    }
                else:
                    self.failed_requests += 1
                    return {
                        "success": False,
                        "status": response.status,
                        "latency": latency
                    }

        except Exception as e:
            self.failed_requests += 1
            latency = time.time() - start
            return {
                "success": False,
                "error": str(e),
                "latency": latency
            }

    async def complete_task(self, session: aiohttp.ClientSession, task_id: int) -> Dict:
        """Complete a task via REST API (triggers recurring task creation)"""
        start = time.time()

        try:
            async with session.patch(
                f"{self.api_url}/api/{self.user_id}/tasks/{task_id}/complete"
            ) as response:
                latency = time.time() - start
                self.total_requests += 1
                self.total_latency += latency

                if response.status == 200:
                    self.successful_requests += 1
                    return {"success": True, "latency": latency}
                else:
                    self.failed_requests += 1
                    return {"success": False, "status": response.status, "latency": latency}

        except Exception as e:
            self.failed_requests += 1
            return {"success": False, "error": str(e)}

    def publish_event_directly(self, event_type: str, task_id: int):
        """Publish event directly to Kafka (bypass REST API)"""
        event = {
            "event_id": str(uuid.uuid4()),
            "event_type": event_type,
            "schema_version": "1.0.0",
            "timestamp": datetime.utcnow().isoformat() + "Z",
            "user_id": self.user_id,
            "task_id": task_id,
            "task_data": {
                "id": task_id,
                "user_id": self.user_id,
                "title": f"Direct Kafka event {task_id}",
                "completed": event_type == "task.completed",
                "recurring_pattern": "daily" if task_id % 3 == 0 else "none"
            }
        }

        self.producer.send("task-events", value=event)
        self.total_requests += 1
        self.successful_requests += 1

    async def run_load_test_rps(self, target_rps: int, duration_seconds: int):
        """
        Run load test at target requests per second

        Args:
            target_rps: Target requests per second
            duration_seconds: Test duration in seconds
        """
        print(f"\nStarting load test:")
        print(f"  Target RPS: {target_rps}")
        print(f"  Duration: {duration_seconds} seconds")
        print(f"  Total requests: {target_rps * duration_seconds}")
        print()

        self.start_time = time.time()

        interval = 1.0 / target_rps  # Time between requests

        async with aiohttp.ClientSession() as session:
            task_num = 0
            created_tasks = []

            while time.time() - self.start_time < duration_seconds:
                loop_start = time.time()

                # Create task
                result = await self.create_task(session, task_num)

                if result["success"]:
                    created_tasks.append(result["task_id"])

                # Every 3rd task, complete a previous one (if available)
                if task_num > 0 and task_num % 3 == 0 and created_tasks:
                    task_to_complete = created_tasks[task_num // 3]
                    await self.complete_task(session, task_to_complete)

                task_num += 1

                # Sleep to maintain target RPS
                elapsed = time.time() - loop_start
                sleep_time = max(0, interval - elapsed)
                if sleep_time > 0:
                    await asyncio.sleep(sleep_time)

                # Print progress every 100 requests
                if task_num % 100 == 0:
                    elapsed_total = time.time() - self.start_time
                    current_rps = task_num / elapsed_total
                    print(f"Progress: {task_num} requests, {current_rps:.1f} RPS")

        self.end_time = time.time()

    async def run_load_test_burst(self, total_events: int, batch_size: int = 100):
        """
        Run burst load test (send as fast as possible)

        Args:
            total_events: Total number of events to send
            batch_size: Number of concurrent requests
        """
        print(f"\nStarting burst load test:")
        print(f"  Total events: {total_events}")
        print(f"  Batch size: {batch_size}")
        print()

        self.start_time = time.time()

        async with aiohttp.ClientSession() as session:
            for batch_start in range(0, total_events, batch_size):
                batch_end = min(batch_start + batch_size, total_events)

                # Create tasks concurrently in batches
                tasks = [
                    self.create_task(session, i)
                    for i in range(batch_start, batch_end)
                ]

                results = await asyncio.gather(*tasks)

                # Print progress
                if batch_end % 1000 == 0:
                    elapsed = time.time() - self.start_time
                    rps = batch_end / elapsed
                    print(f"Progress: {batch_end}/{total_events} events, {rps:.1f} RPS")

        self.end_time = time.time()

    def run_kafka_direct_test(self, total_events: int):
        """
        Run load test by publishing directly to Kafka

        Args:
            total_events: Total number of events to publish
        """
        print(f"\nStarting Kafka direct load test:")
        print(f"  Total events: {total_events}")
        print()

        self.connect_kafka()
        self.start_time = time.time()

        for i in range(total_events):
            event_type = "task.completed" if i % 3 == 0 else "task.created"
            self.publish_event_directly(event_type, task_id=i)

            if i % 1000 == 0 and i > 0:
                elapsed = time.time() - self.start_time
                rps = i / elapsed
                print(f"Progress: {i}/{total_events} events, {rps:.1f} RPS")

        # Flush producer
        self.producer.flush()
        self.end_time = time.time()
        self.close_kafka()

    def print_summary(self):
        """Print load test summary"""
        duration = self.end_time - self.start_time
        avg_latency = self.total_latency / self.total_requests if self.total_requests > 0 else 0
        throughput = self.total_requests / duration if duration > 0 else 0
        success_rate = (self.successful_requests / self.total_requests * 100) if self.total_requests > 0 else 0

        print("\n" + "=" * 60)
        print("LOAD TEST SUMMARY")
        print("=" * 60)
        print(f"Duration:           {duration:.2f} seconds")
        print(f"Total Requests:     {self.total_requests}")
        print(f"Successful:         {self.successful_requests}")
        print(f"Failed:             {self.failed_requests}")
        print(f"Success Rate:       {success_rate:.2f}%")
        print(f"Throughput:         {throughput:.2f} requests/second")
        print(f"Avg Latency:        {avg_latency * 1000:.2f} ms")
        print(f"Events/Minute:      {throughput * 60:.0f}")
        print("=" * 60)

        # Check if target met
        if throughput * 60 >= 10000:
            print("✅ Target met: 10,000+ events/minute")
        else:
            print("❌ Target not met: < 10,000 events/minute")


def main():
    """Main CLI entry point"""
    parser = argparse.ArgumentParser(
        description="Load test Kafka event architecture",
        formatter_class=argparse.RawDescriptionHelpFormatter
    )

    parser.add_argument(
        '--api-url',
        default='http://localhost:8000',
        help='Backend API URL (default: http://localhost:8000)'
    )
    parser.add_argument(
        '--kafka',
        default='localhost:19092',
        help='Kafka bootstrap servers (default: localhost:19092)'
    )
    parser.add_argument(
        '--user-id',
        default='load-test-user',
        help='User ID for test data (default: load-test-user)'
    )

    # Test modes
    mode_group = parser.add_mutually_exclusive_group(required=True)
    mode_group.add_argument(
        '--rps',
        type=int,
        help='Target requests per second (use with --duration)'
    )
    mode_group.add_argument(
        '--events',
        type=int,
        help='Total events to generate (burst mode)'
    )
    mode_group.add_argument(
        '--kafka-direct',
        type=int,
        help='Publish events directly to Kafka (bypass API)'
    )

    parser.add_argument(
        '--duration',
        type=int,
        default=60,
        help='Test duration in seconds (default: 60, use with --rps)'
    )
    parser.add_argument(
        '--batch-size',
        type=int,
        default=100,
        help='Concurrent batch size for burst mode (default: 100)'
    )

    args = parser.parse_args()

    # Create load tester
    tester = LoadTester(
        api_url=args.api_url,
        kafka_bootstrap=args.kafka,
        user_id=args.user_id
    )

    try:
        # Run test based on mode
        if args.rps:
            asyncio.run(tester.run_load_test_rps(args.rps, args.duration))

        elif args.events:
            asyncio.run(tester.run_load_test_burst(args.events, args.batch_size))

        elif args.kafka_direct:
            tester.run_kafka_direct_test(args.kafka_direct)

        # Print summary
        tester.print_summary()

    except KeyboardInterrupt:
        print("\nLoad test interrupted by user")
        if tester.end_time is None:
            tester.end_time = time.time()
        tester.print_summary()

    except Exception as e:
        print(f"\nLoad test failed: {e}")
        return 1

    return 0


if __name__ == '__main__':
    import sys
    sys.exit(main())
