{{- if .Values.secretstore.enabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.secretstore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
{{- end }}
