apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "recurring-task-service.fullname" . }}
  labels:
    {{- include "recurring-task-service.labels" . | nindent 4 }}
data:
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  KAFKA_TOPIC: {{ .Values.kafka.topic | quote }}
  CONSUMER_GROUP_ID: {{ .Values.kafka.consumerGroup | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
